#!/usr/bin/env bash
set -e
if [[ $# -ne 1 ]] ; then
    echo 'Usage: ./setup INSTANCE_NAME'
    exit 1
fi

if [[ "$1" = "testing" ]] || [[ "$1" = "real" ]] || \
       [[ "$1" = "azure" ]] || [[ "$1" = "dev" ]]; then
    echo $1 > instance
else
    echo 'INSTANCE_NAME must be one of [testing, real, azure, dev]'
    exit 1
fi
